#if !macro
import flixel.FlxCamera;
import flixel.FlxGame;
import flixel.FlxState;
import flixel.FlxSubState;
import flixel.tweens.*;
import flixel.util.FlxTimer;
import flixel.FlxSprite;
import flixel.graphics.frames.FlxFrame;
import flixel.math.FlxMatrix;
import flixel.util.FlxDestroyUtil;
import flixel.addons.display.FlxTiledSprite;
import flixel.math.FlxMath;
import flixel.math.FlxRect;
import openfl.display.Sprite;
import funkin.objects.gameplay.NoteSpawner;
import flixel.FlxBasic;
import flixel.FlxG;
import flixel.group.FlxGroup.FlxTypedGroup;
import flixel.group.FlxSpriteGroup.FlxTypedSpriteGroup;
import flixel.sound.FlxSound;
import flixel.util.FlxSort;
import funkin.backend.Conductor;
import funkin.backend.Song;
import funkin.objects.Note;
import funkin.objects.StrumNote;
#end
